### ISSUE TITLE
Saving enable sound option on restart

### ISSUE THREAD

**Issue by rivman** [AkashRajpurohit/clipper#11]
Hello, 
Thanks for this wonderful little piece of software.
The sound OFF option should retain his state on program restart.
Using a file like app-update.yml but for settings, like app-settings.yml ?

Having one option to start with the system may be a great improvement (still can be started with the OS tools).

Thank you.

**Comment by AkashRajpurohit** [comment]
Looks like a good feature, would you like to work on this feature then go ahead and share the PR :)
Ping if you need any assistance. Thanks

**Comment by rivman** [comment]
I'm new to Visual Studio, I will try my best and make a fork for you to see. Many thanks.

**Comment by GirkovArpa** [comment]
Visual Studio Code?
