### ISSUE TITLE
Potential Command Execution vulnerabilities introduced by preload.js

### ISSUE THREAD

**Issue by xiaofen9** [AkashRajpurohit/clipper#13]
Hi,

We found that `preload.js` introduces dangerous API openShellExternal for arbitrary access on unsafe renderer process.
This may lead to remote command execution. 
We suggest that a URL check should be enforced at L15, which enforces an allowlist on trusted urls.

https://github.com/AkashRajpurohit/clipper/blob/d133fde04b4029d69626852206c328363657ad4d/preload.js#L14-L16

**Comment by AkashRajpurohit** [comment]
Makes sense. A validUrl function which check against a list of urls can be a solution. If you are interested to add this, PRs are welcomed for it. I'll look into it. Thank you 😄
