### ISSUE TITLE
Replacing rules for clipboard content

### ISSUE THREAD

**Issue by lazytyper** [AkashRajpurohit/clipper#9]
A clipboard manager could automatically replace certain occurences within the clipboard content, especially for URLs.

The user could add/edit/delete/activate/deactive search and replacing rules, for example

search: "https://www.youtube.com/watch?v="
replace with: "https://youtu.be/"

Links for Youtube would automatically be shortened after copying.

But, in some cases, the content must be kept original. For that, an "undo replace" button would make sense.

**Comment by AkashRajpurohit** [comment]
Thank you for this issue @lazytyper, Do you want to work on this feature?

**Comment by the-gem-dev** [comment]
I would like to work on this feature, I am not sure how but hope to learn in the process

**Comment by AkashRajpurohit** [comment]
@the-gem-dev This project is made using electronjs and reactjs, are you familiar with these framework/library?
Also I would suggest that this feature imo would be a very low priority and very specific to a users experience for which i am not sure if its needed or not. So if you want to learn something from it, I would suggest you to pickup some easy task to get familiar with this process and framework.

If you want to contribute something, I can give you a few ideas and open a separate issue about them. Thank you 😄
